# -*- coding: UTF-8 -*-

SERVER_IP = 'IP_ADDRESS'

SSH_USERNAME = 'SSH_USERNAME'

NEW_USERNAME = 'NEW_USERNAME'
NEW_USER_PUBLIC_KEY = 'NEW_USER_PUBLIC_KEY'

MQTT_USER = 'openhabian'
MQTT_PASSWORD = 'MQTT_PASSWORD'

INFLUXDB_PASSWORD_ADMIN = 'INFLUXDB_PASSWORD_ADMIN'
INFLUXDB_DB_NAME = 'openhab_db'

INFLUXDB_USERNAME_OPENHAB = 'openhab'
INFLUXDB_PASSWORD_OPENHAB = 'INFLUXDB_PASSWORD_OPENHAB'

INFLUXDB_USERNAME_GRAFANA = 'grafana'
INFLUXDB_PASSWORD_GRAFANA = 'INFLUXDB_PASSWORD_GRAFANA'
