# config file version
apiVersion: 1

#deleteDatasources:
#  - name: openhab_home
#    orgId: 1

datasources:
- name: openhab_home
  type: influxdb
  access: proxy
  orgId: 1
  url: http://localhost:8086

  user: DB_USER
  password: DB_PASSWORD
  database: DB_NAME

  basicAuth: true
  basicAuthUser: BASIC_AUTH_USER
  basicAuthPassword: BASIC_AUTH_PASSWORD
